# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Документ')),
                ('kurs', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='docs')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название предмета')),
                ('code_name', models.SlugField(max_length=20, unique=True, verbose_name='URL префикс (только латинские быквы и символы - и _')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject', verbose_name='Предмет'),
        ),
    ]
