# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code_name',
            field=models.SlugField(max_length=20, unique=True, verbose_name='URL префикс'),
        ),
    ]
