# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160710_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='magistratura',
            field=models.BooleanField(default=False, verbose_name='Магистратура'),
        ),
    ]
