# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_magistratura'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='kurs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Курс'),
        ),
    ]
