# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_masked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='masked',
            field=models.BooleanField(default=True, verbose_name='Скрытый'),
        ),
    ]
